# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyBio',
            fields=[
                ('id_baby', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('baby_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('weight_birth', models.IntegerField()),
                ('height_birth', models.IntegerField()),
                ('headcircumference_birth', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babyname', models.CharField(max_length=50)),
                ('check', models.CharField(choices=[('weight', 'Weight'), ('height', 'Height'), ('headcircumference', 'HeadCircumference'), ('immunization', 'Immunization')], max_length=30)),
                ('value', models.IntegerField()),
                ('imun_value', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='kelola.BabyBio')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Health', 'health'), ('Growing', 'growing'), ('Development', 'development'), ('Immunization', 'immunization')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
