# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelola', '0002_remove_history_babyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
