# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kelola', '0004_auto_20170411_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_event', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='babybio',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'laki-laki'), ('Perempuan', 'perempuan')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='babybio',
            name='parent_email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='imun_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
