# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelola', '0005_auto_20170417_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='imun_value',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
